### PR TITLE
README fixes

### PR DESCRIPTION
**Pull request by ghost**
Corrected small typos like `mdoern` and removed the `Todo` in `#Screenshots`

### CODE REVIEW

**Comment by moeenio** [comment]
I think you can just remove the "screenshots" section  and keep the screenshot at the top (which is btw outdated, also, i'm not sure that counts as a typo)

**Comment by moeenio** [comment]
> and keep the screenshot at the top

@delnyn

**Comment by ghost** [comment]
Corrected small typos like `mdoern` and removed the `##Screenshots`

**Comment by moeenio** [comment]
okay, nice, thanks

**Pull request merged**
